# Generated by Django 3.0.8 on 2020-07-29 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_cin', models.DateField()),
                ('b_cot', models.DateField()),
                ('b_A', models.IntegerField(default=1, max_length=2)),
                ('b_C', models.IntegerField(default=0, max_length=2)),
                ('b_dt', models.DateField(auto_now_add=True)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booker.Room')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
