# Generated by Django 3.0.8 on 2020-07-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='b_pid',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
